course = "python programming"
print(len(course))
print(course[0])
print(course[-1])
print(course[0:17])
print(course[0:-1])
print(course[-2:-1])
print(course[-1:-2])
print(course[0:])
print(course[:3])
print(course[:])
