course = "   python Programming    "
capital_course = print(course.upper())
lower_course = print(course.lower())
title_course = print(course.title())
stripped_course = print(course.strip())
lstripped_course = print(course.lstrip())
rstripped_course = print(course.rstrip())
print(course.rstrip()+"hello")
print(course.find("pro"))
print(course.find("Pro"))
print(course.replace("p", "j"))
print("Pro" in course)
print("pro" in course)
print("chandu" not in course)
print(course.replace("i", "chandu"))
course = course.replace("i", "chandu")
print(course)
print("chandu" not in course)
